# set motor configure
# control mode: [torque, impedance, velocity, position]
# p, d gain is Impedance gain
motors:
  - name: "LHY"
    slave_index: 8
    p_gain: 3000
    d_gain: 55
    control_mode: impedance
  - name: "LHP"
    slave_index: 9
    p_gain: 7500
    d_gain: 125
    control_mode: impedance
  - name: "LKP"
    slave_index: 10
    p_gain: 15000
    d_gain: 250
    control_mode: impedance
  - name: "LW"
    slave_index: 11
    p_gain: 600
    d_gain: 1
    control_mode: velocity
  - name: "RHY"
    slave_index: 4
    p_gain: 3000
    d_gain: 55
    control_mode: position
  - name: "RHP"
    slave_index: 5
    p_gain: 7500
    d_gain: 125
    control_mode: position
  - name: "RKP"
    slave_index: 6
    p_gain: 15000
    d_gain: 250
    control_mode: position
  - name: "RW"
    slave_index: 7
    p_gain: 600
    d_gain: 1
    control_mode: torque