# set motor configure
# control mode: [torque, impedance, velocity, position]
# p, d gain is Impedance gain
motors:
  - name: "TEST"
    slave_index: 1
    p_gain: 3000
    d_gain: 55
    control_mode: torque_m
